language: rust
cache: cargo
rust:
    - stable 
    - beta
    - nightly
matrix:
    allow_failures:
      - rust: beta
      - rust: nightly
before_install:
    - sudo apt-get update && sudo apt-get build-dep libsdl2-dev